// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/conduitio/conduit-connector-sdk/cmd/paramgen

package cassandra

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (DestinationConfig) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"auth.basic.password": {
			Default:     "",
			Description: "Password, only if basic auth is used.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.basic.username": {
			Default:     "",
			Description: "Username, only if basic auth is used.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"auth.mechanism": {
			Default:     "none",
			Description: "Authentication mechanism used by Cassandra.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"none", "basic"}},
			},
		},
		"keyspace": {
			Default:     "",
			Description: "The keyspace name that has the table (similar to a database in a relational database system).",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"nodes": {
			Default:     "",
			Description: "Comma separated list of Cassandra nodes' addresses (at least one), ex: 127.0.0.1:9042,127.0.0.2:8080",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"table": {
			Default:     "",
			Description: "The table name.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
